#!/usr/bin/env bash
set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color
BOLD='\033[1m'

# Get absolute path to this script's directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VENV_PATH="$SCRIPT_DIR/.venv"
MINIDANI_SCRIPT="$SCRIPT_DIR/minidani.py"

echo ""
echo -e "${BLUE}${BOLD}🦞 MiniDani Installer${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Step 1: Check Python version
echo -e "${BOLD}[1/4] Checking Python...${NC}"

if ! command -v python3 &> /dev/null; then
    echo -e "  ${RED}❌ Python 3 not found${NC}"
    echo ""
    echo "Please install Python 3.8 or higher:"
    echo "  Ubuntu/Debian: sudo apt install python3 python3-venv"
    echo "  macOS: brew install python3"
    echo "  Arch: sudo pacman -S python"
    exit 1
fi

# Get Python version
PYTHON_VERSION=$(python3 --version | cut -d' ' -f2)
PYTHON_MAJOR=$(echo "$PYTHON_VERSION" | cut -d'.' -f1)
PYTHON_MINOR=$(echo "$PYTHON_VERSION" | cut -d'.' -f2)

if [ "$PYTHON_MAJOR" -lt 3 ] || ([ "$PYTHON_MAJOR" -eq 3 ] && [ "$PYTHON_MINOR" -lt 8 ]); then
    echo -e "  ${RED}❌ Python $PYTHON_VERSION found (minimum 3.8 required)${NC}"
    exit 1
fi

echo -e "  ${GREEN}✅ Python $PYTHON_VERSION (minimum 3.8 required)${NC}"
echo ""

# Step 2: Setup virtual environment
echo -e "${BOLD}[2/4] Setting up virtual environment...${NC}"

if [ -d "$VENV_PATH" ]; then
    echo -e "  ${YELLOW}⚠️  Existing venv found, reinstalling dependencies...${NC}"
    rm -rf "$VENV_PATH"
fi

python3 -m venv "$VENV_PATH"
echo -e "  ${GREEN}✅ Virtual environment created at: $VENV_PATH${NC}"

# Activate venv and install dependencies
source "$VENV_PATH/bin/activate"
pip install --upgrade pip > /dev/null 2>&1
pip install -r "$SCRIPT_DIR/requirements.txt" > /dev/null 2>&1
deactivate

echo -e "  ${GREEN}✅ Dependencies installed${NC}"
echo ""

# Step 3: Setup OpenCode agents
echo -e "${BOLD}[3/5] Setting up OpenCode agents...${NC}"

OPENCODE_DIR="$HOME/.opencode"
AGENTS_SOURCE="$SCRIPT_DIR/.opencode/agents"
AGENTS_LINK="$OPENCODE_DIR/agents"

# Create .opencode directory if it doesn't exist
mkdir -p "$OPENCODE_DIR"

# Remove existing agents link/directory if present
if [ -L "$AGENTS_LINK" ]; then
    echo -e "  ${YELLOW}⚠️  Removing existing agents symlink${NC}"
    rm "$AGENTS_LINK"
elif [ -d "$AGENTS_LINK" ]; then
    echo -e "  ${YELLOW}⚠️  Backing up existing agents directory${NC}"
    mv "$AGENTS_LINK" "${AGENTS_LINK}.backup.$(date +%s)"
fi

# Create symlink
ln -sf "$AGENTS_SOURCE" "$AGENTS_LINK"

if [ -L "$AGENTS_LINK" ] && [ -d "$AGENTS_LINK" ]; then
    echo -e "  ${GREEN}✅ Agents linked: ~/.opencode/agents/ -> $AGENTS_SOURCE${NC}"
    echo -e "  ${BLUE}📝 Available agents: manager, blue-team, red-team, judge, branch-namer, pr-creator${NC}"
else
    echo -e "  ${RED}❌ Failed to create agents symlink${NC}"
    exit 1
fi
echo ""

# Step 4: Find installation directory
echo -e "${BOLD}[4/5] Finding installation directory...${NC}"

POSSIBLE_BINS=(
    "$HOME/.local/bin"
    "$HOME/bin"
    "/usr/local/bin"
)

INSTALL_DIR=""
for bin_dir in "${POSSIBLE_BINS[@]}"; do
    if [[ ":$PATH:" == *":$bin_dir:"* ]]; then
        INSTALL_DIR="$bin_dir"
        echo -e "  ${GREEN}✅ Using: $INSTALL_DIR (already in PATH)${NC}"
        break
    fi
done

if [ -z "$INSTALL_DIR" ]; then
    INSTALL_DIR="$HOME/.local/bin"
    mkdir -p "$INSTALL_DIR"
    
    echo -e "  ${YELLOW}⚠️  No suitable directory found in PATH${NC}"
    echo -e "  ${BLUE}📁 Using: $INSTALL_DIR${NC}"
    echo ""
    echo -e "  ${BOLD}To use 'minidani' command, add this to your shell config:${NC}"
    echo ""
    
    if [ -n "$BASH_VERSION" ]; then
        echo -e "  ${BLUE}For bash:${NC}"
        echo "    echo 'export PATH=\"\$HOME/.local/bin:\$PATH\"' >> ~/.bashrc"
        echo "    source ~/.bashrc"
    elif [ -n "$ZSH_VERSION" ]; then
        echo -e "  ${BLUE}For zsh:${NC}"
        echo "    echo 'export PATH=\"\$HOME/.local/bin:\$PATH\"' >> ~/.zshrc"
        echo "    source ~/.zshrc"
    else
        echo -e "  ${BLUE}Add to your shell config:${NC}"
        echo "    export PATH=\"\$HOME/.local/bin:\$PATH\""
    fi
    echo ""
fi

# Step 5: Create wrapper script
echo -e "${BOLD}[5/5] Creating wrapper script...${NC}"

WRAPPER_PATH="$INSTALL_DIR/minidani"

cat > "$WRAPPER_PATH" << EOF
#!/usr/bin/env bash
# MiniDani wrapper - auto-generated by install.sh

# Activate virtual environment
source "$VENV_PATH/bin/activate"

# Run minidani.py with all arguments
python3 "$MINIDANI_SCRIPT" "\$@"

# Exit with same code as minidani.py
exit \$?
EOF

chmod +x "$WRAPPER_PATH"
echo -e "  ${GREEN}✅ Executable created: $WRAPPER_PATH${NC}"
echo ""

# Final message
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo -e "${GREEN}${BOLD}✅ Installation complete!${NC}"
echo ""
echo -e "${BOLD}Usage:${NC}"
echo "  cd /path/to/your/project"
echo "  minidani \"Your prompt here\""
echo ""
echo -e "${BOLD}With file:${NC}"
echo "  minidani \"\$(cat prompt.md)\""
echo ""
echo -e "${BOLD}OpenCode agents:${NC}"
echo "  Agents are now available globally at ~/.opencode/agents/"
echo "  Any OpenCode project can use: @manager, @blue-team, @red-team, etc."
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
